### ISSUE TITLE
Why vendor Directory

### ISSUE THREAD

**Issue by amayer5125** [alexellis/hash-browns#6]
I'm more just curious about this. I have seen a couple projects include the vendor directory in their git repo along with the *Gopkg* files. Wouldn't you just need one or the other? Is there a reason to include this directory?

**Comment by alexellis** [comment]
Feel free to read up on how vendoring in Go works on Google. I won't attempt to explain it here but vendor is committed along with Gopkg.*. These files are generated by the dep tool (you can find that on Google). See the contributing guide for openfaas/faas for more examples.
