### ISSUE TITLE
Pin Prometheus version and migrate config

### ISSUE THREAD

**Issue by alexellis** [alexellis/hash-browns#7]
The Prometheus version of the Docker image in docker-compose.yml is not pinned to a specific version, this means breaking changes in the config prometheus.yml will break the example.

Tasks:
- [ ] Pin Prometheus version to latest
- [ ] Migrate config in prometheus.yml
- [ ] Fully test

https://github.com/alexellis/hash-browns/blob/master/prometheus.yml

**Comment by alexellis** [comment]
See also: 
https://github.com/alexellis/hash-browns/blob/master/CONTRIBUTING.md

**Comment by nathanmkaya** [comment]
Can I take this?

**Comment by alexellis** [comment]
Hi yes if you're able to complete the whole task and the end to end testing then please do. Alex
