### ISSUE TITLE
Question about histogram metric

### ISSUE THREAD

**Issue by theshivachutani** [alexellis/hash-browns#9]
https://github.com/alexellis/hash-browns/blob/master/main.go:101
The value of "code" is never set to 200 after processing the hash.

**Comment by alexellis** [comment]
Hey @theshivachutani thanks for your interest

In order to help out here, I'd just ask for the following:

1) What you saw (steps)
2) What you did to see it (steps)
3) What your suggested fix is

Thanks,

Alex
